[pytest]
pythonpath = .
testpaths = tests
norecursedirs = .git .tox venv env .venv node_modules build dist *.egg-info

addopts =
    --ff
    --tb=short
    --strict-markers
    -q
    --cache-clear

python_classes = Test*
python_files = test_*.py
python_functions = test_*

markers =
    unit: Fast, isolated tests (No DB/Network)
    integration: Slower tests requiring external state
    slow: Tests taking > 1s